name: CI with Centralized Security Setup-

on:
  workflow_dispatch:
  push:
    branches: [ main, develop ]
    tags:
      - 'v*.*.*'
    paths-ignore:
      - 'Kubernetes/**'
      - 'Docker/**'
      - 'security_compliance/policy/**'
      - '.github/workflows/policy-check.yml'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'Kubernetes/**'
      - 'Docker/**'
      - 'security_compliance/policy/**'
      - '.github/workflows/policy-check.yml'

permissions:
  contents: read
  packages: write
  id-token: write
  actions: read
  security-events: write

env:
  BUILD_TYPE: Release
  IMAGE_NAME: ghcr.io/okbobm/hash-service

jobs:
  # Step 1: C++ Security with centralized setup
  call-workflow-passing-data:    
    uses: rmtechtransfer1/github-actions-security/.github/workflows/cmake-security.yml@main
    with:
      build-type: Release
      source-dir: '.'
      build-dir: 'build'
      cmake-args: '-G Ninja'
      upload-artifacts: true
    secrets: inherit  
    permissions:
      contents: read
      security-events: write

 